package model

// RecipeDefinition captures a production recipe.
type RecipeDefinition struct {
	HandcraftAllowed bool           `json:"handcraft_allowed"`
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Inputs           []ItemAmount   `json:"inputs"`
	Outputs          []ItemAmount   `json:"outputs"`
	Byproducts       []ItemAmount   `json:"byproducts,omitempty"`
	Duration         int            `json:"duration"`
	EnergyCost       int            `json:"energy_cost"`
	BuildingTypes    []BuildingType `json:"building_types"`
	TechUnlock       []string       `json:"tech_unlock,omitempty"`
}

// AllOutputs returns the main outputs plus byproducts.
func (r RecipeDefinition) AllOutputs() []ItemAmount {
	if len(r.Byproducts) == 0 {
		return r.Outputs
	}
	outs := make([]ItemAmount, 0, len(r.Outputs)+len(r.Byproducts))
	outs = append(outs, r.Outputs...)
	outs = append(outs, r.Byproducts...)
	return outs
}

var recipeCatalog = map[string]RecipeDefinition{
	"smelt_iron": {
		HandcraftAllowed: true,
		ID:               "smelt_iron",
		Name:             "Smelt Iron",
		Inputs:           []ItemAmount{{ItemID: ItemIronOre, Quantity: 1}},
		Outputs:          []ItemAmount{{ItemID: ItemIronIngot, Quantity: 1}},
		Duration:         60,
		EnergyCost:       1,
		BuildingTypes:    []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
	},
	"smelt_copper": {
		HandcraftAllowed: true,
		ID:               "smelt_copper",
		Name:             "Smelt Copper",
		Inputs:           []ItemAmount{{ItemID: ItemCopperOre, Quantity: 1}},
		Outputs:          []ItemAmount{{ItemID: ItemCopperIngot, Quantity: 1}},
		Duration:         60,
		EnergyCost:       1,
		BuildingTypes:    []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
	},
	"smelt_stone": {
		HandcraftAllowed: true,
		ID:               "smelt_stone",
		Name:             "Smelt Stone",
		Inputs:           []ItemAmount{{ItemID: ItemStoneOre, Quantity: 1}},
		Outputs:          []ItemAmount{{ItemID: ItemStoneBrick, Quantity: 1}},
		Duration:         50,
		EnergyCost:       1,
		BuildingTypes:    []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:       []string{"automatic_metallurgy"},
	},
	"smelt_magnet": {
		HandcraftAllowed: true,
		ID:               "smelt_magnet",
		Name:             "Smelt Magnet",
		Inputs:           []ItemAmount{{ItemID: ItemIronOre, Quantity: 1}},
		Outputs:          []ItemAmount{{ItemID: ItemMagnet, Quantity: 1}},
		Duration:         60,
		EnergyCost:       1,
		BuildingTypes:    []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
	},
	"smelt_silicon": {
		ID:            "smelt_silicon",
		Name:          "Smelt Silicon",
		Inputs:        []ItemAmount{{ItemID: ItemSiliconOre, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemSiliconIngot, Quantity: 1}},
		Duration:      60,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:    []string{"smelting_purification"},
	},
	"smelt_titanium": {
		ID:            "smelt_titanium",
		Name:          "Smelt Titanium",
		Inputs:        []ItemAmount{{ItemID: ItemTitaniumOre, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemTitaniumIngot, Quantity: 1}},
		Duration:      60,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:    []string{"titanium_smelting"},
	},
	"coal_to_graphite": {
		HandcraftAllowed: true,
		ID:               "coal_to_graphite",
		Name:             "Coal To Energetic Graphite",
		Inputs:           []ItemAmount{{ItemID: ItemCoal, Quantity: 2}},
		Outputs:          []ItemAmount{{ItemID: ItemEnergeticGraphite, Quantity: 1}},
		Duration:         30,
		BuildingTypes:    []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:       []string{"smelting_purification"},
	},
	"oil_fractionation": {
		ID:            "oil_fractionation",
		Name:          "等离子精炼",
		Inputs:        []ItemAmount{{ItemID: ItemCrudeOil, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemRefinedOil, Quantity: 2}},
		Byproducts:    []ItemAmount{{ItemID: ItemHydrogen, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeOilRefinery},
		TechUnlock:    []string{"plasma_refining"},
	},
	"xray_cracking": {
		ID:            "xray_cracking",
		Name:          "X 射线裂解",
		Inputs:        []ItemAmount{{ItemID: ItemRefinedOil, Quantity: 1}, {ItemID: ItemHydrogen, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemHydrogen, Quantity: 3}},
		Byproducts:    []ItemAmount{{ItemID: ItemEnergeticGraphite, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeOilRefinery},
		TechUnlock:    []string{"xray_cracking"},
	},
	"reformed_refinement": {
		ID:            "reformed_refinement",
		Name:          "重整精炼",
		Inputs:        []ItemAmount{{ItemID: ItemRefinedOil, Quantity: 2}, {ItemID: ItemHydrogen, Quantity: 1}, {ItemID: ItemCoal, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemRefinedOil, Quantity: 3}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeOilRefinery},
		TechUnlock:    []string{"reformed_refinement"},
	},
	"plastic": {
		ID:            "plastic",
		Name:          "Plastic",
		Inputs:        []ItemAmount{{ItemID: ItemRefinedOil, Quantity: 1}, {ItemID: ItemEnergeticGraphite, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemPlastic, Quantity: 2}},
		Duration:      40,
		EnergyCost:    1,
		BuildingTypes: []BuildingType{BuildingTypeChemicalPlant, BuildingTypeQuantumChemicalPlant},
		TechUnlock:    []string{"basic_chemical"},
	},
	"sulfuric_acid": {
		ID:            "sulfuric_acid",
		Name:          "Sulfuric Acid",
		Inputs:        []ItemAmount{{ItemID: ItemRefinedOil, Quantity: 2}, {ItemID: ItemStoneOre, Quantity: 1}, {ItemID: ItemWater, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemSulfuricAcid, Quantity: 2}},
		Duration:      60,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeChemicalPlant, BuildingTypeQuantumChemicalPlant},
		TechUnlock:    []string{"basic_chemical"},
	},
	"graphene_from_graphite": {
		ID:            "graphene_from_graphite",
		Name:          "Graphene From Graphite",
		Inputs:        []ItemAmount{{ItemID: ItemEnergeticGraphite, Quantity: 2}, {ItemID: ItemSulfuricAcid, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemGraphene, Quantity: 2}},
		Duration:      50,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeChemicalPlant, BuildingTypeQuantumChemicalPlant},
		TechUnlock:    []string{"superconductor"},
	},
	"carbon_nanotube": {
		ID:            "carbon_nanotube",
		Name:          "Carbon Nanotube",
		Inputs:        []ItemAmount{{ItemID: ItemGraphene, Quantity: 2}, {ItemID: ItemTitaniumIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemCarbonNanotube, Quantity: 2}},
		Duration:      70,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeChemicalPlant, BuildingTypeQuantumChemicalPlant},
		TechUnlock:    []string{"high_strength_material"},
	},
	"gear": {
		HandcraftAllowed: true,
		ID:               "gear",
		Name:             "Gear",
		Inputs:           []ItemAmount{{ItemID: ItemIronIngot, Quantity: 1}},
		Outputs:          []ItemAmount{{ItemID: ItemGear, Quantity: 1}},
		Duration:         20,
		BuildingTypes:    []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
	},
	"logistics_bot": {ID: "logistics_bot", Name: "Logistics Bot", Inputs: []ItemAmount{{ItemID: ItemMotor, Quantity: 1}, {ItemID: ItemCircuitBoard, Quantity: 1}, {ItemID: ItemIronIngot, Quantity: 2}}, Outputs: []ItemAmount{{ItemID: ItemLogisticsBot, Quantity: 1}}, Duration: 60, BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3}, TechUnlock: []string{"distribution_logistics"}},
	"logistics_drone": {
		ID: "logistics_drone", Name: "Logistics Drone", Inputs: []ItemAmount{{ItemID: ItemMotor, Quantity: 2}, {ItemID: ItemProcessor, Quantity: 2}, {ItemID: ItemIronIngot, Quantity: 5}},
		Outputs: []ItemAmount{{ItemID: ItemLogisticsDrone, Quantity: 1}}, Duration: 120,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3}, TechUnlock: []string{"planetary_logistics"},
	},
	"logistics_vessel": {
		ID: "logistics_vessel", Name: "Logistics Vessel", Inputs: []ItemAmount{{ItemID: ItemMotor, Quantity: 2}, {ItemID: ItemProcessor, Quantity: 10}, {ItemID: ItemTitaniumAlloy, Quantity: 10}},
		Outputs: []ItemAmount{{ItemID: ItemLogisticsVessel, Quantity: 1}}, Duration: 300,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3}, TechUnlock: []string{"interstellar_logistics"},
	},
	"motor": {
		ID:            "motor",
		Name:          "Motor",
		Inputs:        []ItemAmount{{ItemID: ItemGear, Quantity: 1}, {ItemID: ItemCircuitBoard, Quantity: 1}, {ItemID: ItemIronIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemMotor, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"electromagnetic_drive"},
	},
	"circuit_board": {
		HandcraftAllowed: true,
		ID:               "circuit_board",
		Name:             "Circuit Board",
		Inputs:           []ItemAmount{{ItemID: ItemIronIngot, Quantity: 1}, {ItemID: ItemCopperIngot, Quantity: 1}},
		Outputs:          []ItemAmount{{ItemID: ItemCircuitBoard, Quantity: 1}},
		Duration:         30,
		BuildingTypes:    []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
	},
	"magnetic_coil": {
		HandcraftAllowed: true,
		ID:               "magnetic_coil",
		Name:             "Magnetic Coil",
		Inputs:           []ItemAmount{{ItemID: ItemMagnet, Quantity: 2}, {ItemID: ItemCopperIngot, Quantity: 1}},
		Outputs:          []ItemAmount{{ItemID: ItemMagneticCoil, Quantity: 2}},
		Duration:         30,
		BuildingTypes:    []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
	},
	"microcrystalline_component": {
		ID:            "microcrystalline_component",
		Name:          "Microcrystalline Component",
		Inputs:        []ItemAmount{{ItemID: ItemSiliconIngot, Quantity: 2}, {ItemID: ItemCopperIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemMicrocrystalline, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"semiconductor"},
	},
	"processor": {
		ID:            "processor",
		Name:          "Processor",
		Inputs:        []ItemAmount{{ItemID: ItemCircuitBoard, Quantity: 2}, {ItemID: ItemMicrocrystalline, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemProcessor, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"processor"},
	},
	"titanium_crystal": {
		ID:            "titanium_crystal",
		Name:          "Titanium Crystal",
		Inputs:        []ItemAmount{{ItemID: ItemTitaniumIngot, Quantity: 2}, {ItemID: ItemGraphene, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemTitaniumCrystal, Quantity: 1}},
		Duration:      80,
		EnergyCost:    4,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"high_strength_crystal"},
	},
	"titanium_alloy": {
		ID:            "titanium_alloy",
		Name:          "Titanium Alloy",
		Inputs:        []ItemAmount{{ItemID: ItemTitaniumIngot, Quantity: 4}, {ItemID: ItemEnergeticGraphite, Quantity: 2}, {ItemID: ItemSulfuricAcid, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemTitaniumAlloy, Quantity: 2}},
		Duration:      100,
		EnergyCost:    6,
		BuildingTypes: []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:    []string{"titanium_alloy"},
	},
	"frame_material": {
		ID:            "frame_material",
		Name:          "Frame Material",
		Inputs:        []ItemAmount{{ItemID: ItemCarbonNanotube, Quantity: 2}, {ItemID: ItemTitaniumAlloy, Quantity: 1}, {ItemID: ItemProcessor, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemFrameMaterial, Quantity: 1}},
		Duration:      120,
		EnergyCost:    6,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"lightweight_structure"},
	},
	"quantum_chip": {
		ID:            "quantum_chip",
		Name:          "Quantum Chip",
		Inputs:        []ItemAmount{{ItemID: ItemProcessor, Quantity: 2}, {ItemID: ItemMicrocrystalline, Quantity: 2}, {ItemID: ItemCarbonNanotube, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemQuantumChip, Quantity: 1}},
		Duration:      140,
		EnergyCost:    8,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"quantum_chip"},
	},
	"graphene_from_fire_ice": {
		ID:            "graphene_from_fire_ice",
		Name:          "Graphene From Fire Ice",
		Inputs:        []ItemAmount{{ItemID: ItemFireIce, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemGraphene, Quantity: 2}},
		Byproducts:    []ItemAmount{{ItemID: ItemHydrogen, Quantity: 1}},
		Duration:      50,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"superconductor"},
	},
	"crystal_silicon_from_fractal": {
		ID:            "crystal_silicon_from_fractal",
		Name:          "Crystal Silicon From Fractal Silicon",
		Inputs:        []ItemAmount{{ItemID: ItemFractalSilicon, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemCrystalSilicon, Quantity: 1}},
		Duration:      30,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"crystal_smelting"},
	},
	"photon_combiner_from_grating": {
		ID:            "photon_combiner_from_grating",
		Name:          "Photon Combiner",
		Inputs:        []ItemAmount{{ItemID: ItemGratingCrystal, Quantity: 1}, {ItemID: ItemCircuitBoard, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemPhotonCombiner, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"photon_conversion"},
	},
	"particle_container_from_monopole": {
		ID:            "particle_container_from_monopole",
		Name:          "Particle Container",
		Inputs:        []ItemAmount{{ItemID: ItemMonopoleMagnet, Quantity: 1}, {ItemID: ItemTitaniumIngot, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemParticleContainer, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"particle_container"},
	},
	"deuterium_collision": {
		ID:            "deuterium_collision",
		Name:          "Deuterium Collision",
		Inputs:        []ItemAmount{{ItemID: ItemHydrogen, Quantity: 10}},
		Outputs:       []ItemAmount{{ItemID: ItemDeuterium, Quantity: 5}},
		Duration:      300,
		EnergyCost:    24,
		BuildingTypes: []BuildingType{BuildingTypeMiniatureParticleCollider},
		TechUnlock:    []string{"miniature_collider"},
	},
	"antimatter": {
		ID:            "antimatter",
		Name:          "Antimatter",
		Inputs:        []ItemAmount{{ItemID: ItemCriticalPhoton, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemAntimatter, Quantity: 2}},
		Byproducts:    []ItemAmount{{ItemID: ItemHydrogen, Quantity: 2}},
		Duration:      120,
		EnergyCost:    8,
		BuildingTypes: []BuildingType{BuildingTypeMiniatureParticleCollider},
		TechUnlock:    []string{"dirac_inversion"},
	},
	"strange_matter": {
		ID:            "strange_matter",
		Name:          "Strange Matter",
		Inputs:        []ItemAmount{{ItemID: ItemParticleContainer, Quantity: 2}, {ItemID: ItemDeuterium, Quantity: 10}, {ItemID: ItemIronIngot, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemStrangeMatter, Quantity: 1}},
		Duration:      480,
		EnergyCost:    6,
		BuildingTypes: []BuildingType{BuildingTypeMiniatureParticleCollider},
		TechUnlock:    []string{"strange_matter"},
	},
	"annihilation_constraint_sphere": {
		ID:            "annihilation_constraint_sphere",
		Name:          "Annihilation Constraint Sphere",
		Inputs:        []ItemAmount{{ItemID: ItemParticleContainer, Quantity: 1}, {ItemID: ItemProcessor, Quantity: 1}, {ItemID: ItemDeuteriumFuelRod, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemAnnihilationConstraintSphere, Quantity: 1}},
		Duration:      120,
		EnergyCost:    3,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"annihilation"},
	},
	"hydrogen_fuel_rod": {
		ID:            "hydrogen_fuel_rod",
		Name:          "Hydrogen Fuel Rod",
		Inputs:        []ItemAmount{{ItemID: ItemHydrogen, Quantity: 5}, {ItemID: ItemTitaniumIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemHydrogenFuelRod, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"hydrogen_fuel"},
	},
	"deuterium_fuel_rod": {
		ID:            "deuterium_fuel_rod",
		Name:          "Deuterium Fuel Rod",
		Inputs:        []ItemAmount{{ItemID: ItemDeuterium, Quantity: 5}, {ItemID: ItemTitaniumIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemDeuteriumFuelRod, Quantity: 1}},
		Duration:      80,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"mini_fusion"},
	},
	"small_carrier_rocket": {
		ID:            "small_carrier_rocket",
		Name:          "Small Carrier Rocket",
		Inputs:        []ItemAmount{{ItemID: ItemFrameMaterial, Quantity: 2}, {ItemID: ItemDeuteriumFuelRod, Quantity: 2}, {ItemID: ItemQuantumChip, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemSmallCarrierRocket, Quantity: 1}},
		Duration:      200,
		EnergyCost:    12,
		BuildingTypes: []BuildingType{BuildingTypeVerticalLaunchingSilo},
		TechUnlock:    []string{"vertical_launching"},
	},
	"antimatter_fuel_rod": {
		ID:            "antimatter_fuel_rod",
		Name:          "Antimatter Fuel Rod",
		Inputs:        []ItemAmount{{ItemID: ItemAntimatter, Quantity: 2}, {ItemID: ItemHydrogen, Quantity: 2}, {ItemID: ItemAnnihilationConstraintSphere, Quantity: 1}, {ItemID: ItemTitaniumIngot, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemAntimatterFuelRod, Quantity: 1}},
		Duration:      150,
		EnergyCost:    12,
		BuildingTypes: []BuildingType{BuildingTypeRecomposingAssembler},
		TechUnlock:    []string{"annihilation"},
	},
	"fuel_rod_recycling": {
		ID:            "fuel_rod_recycling",
		Name:          "Fuel Rod Recycling",
		Inputs:        []ItemAmount{{ItemID: ItemDeuteriumFuelRod, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemDeuterium, Quantity: 2}, {ItemID: ItemTitaniumIngot, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
	},
	"electromagnetic_matrix": {
		ID:            "electromagnetic_matrix",
		Name:          "Electromagnetic Matrix",
		Inputs:        []ItemAmount{{ItemID: ItemMagneticCoil, Quantity: 1}, {ItemID: ItemCircuitBoard, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemElectromagneticMatrix, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3, BuildingTypeMatrixLab, BuildingTypeSelfEvolutionLab},
	},
	"energy_matrix": {
		ID:            "energy_matrix",
		Name:          "Energy Matrix",
		Inputs:        []ItemAmount{{ItemID: ItemEnergeticGraphite, Quantity: 1}, {ItemID: ItemHydrogen, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemEnergyMatrix, Quantity: 1}},
		Duration:      80,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3, BuildingTypeMatrixLab, BuildingTypeSelfEvolutionLab},
		TechUnlock:    []string{"energy_matrix"},
	},
	"structure_matrix": {
		ID:            "structure_matrix",
		Name:          "Structure Matrix",
		Inputs:        []ItemAmount{{ItemID: ItemTitaniumIngot, Quantity: 1}, {ItemID: ItemPlastic, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemStructureMatrix, Quantity: 1}},
		Duration:      90,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3, BuildingTypeMatrixLab, BuildingTypeSelfEvolutionLab},
		TechUnlock:    []string{"structure_matrix"},
	},
	"information_matrix": {
		ID:            "information_matrix",
		Name:          "Information Matrix",
		Inputs:        []ItemAmount{{ItemID: ItemProcessor, Quantity: 2}, {ItemID: ItemQuantumChip, Quantity: 1}, {ItemID: ItemCarbonNanotube, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemInformationMatrix, Quantity: 1}},
		Duration:      120,
		EnergyCost:    6,
		BuildingTypes: []BuildingType{BuildingTypeMatrixLab, BuildingTypeRecomposingAssembler, BuildingTypeSelfEvolutionLab},
		TechUnlock:    []string{"information_matrix"},
	},
	"gravity_matrix": {
		ID:            "gravity_matrix",
		Name:          "Gravity Matrix",
		Inputs:        []ItemAmount{{ItemID: ItemQuantumChip, Quantity: 2}, {ItemID: ItemStrangeMatter, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemGravityMatrix, Quantity: 1}},
		Duration:      150,
		EnergyCost:    8,
		BuildingTypes: []BuildingType{BuildingTypeMatrixLab, BuildingTypeRecomposingAssembler, BuildingTypeSelfEvolutionLab},
		TechUnlock:    []string{"gravity_matrix"},
	},
	"universe_matrix": {
		ID:   "universe_matrix",
		Name: "Universe Matrix",
		Inputs: []ItemAmount{
			{ItemID: ItemElectromagneticMatrix, Quantity: 1},
			{ItemID: ItemEnergyMatrix, Quantity: 1},
			{ItemID: ItemStructureMatrix, Quantity: 1},
			{ItemID: ItemInformationMatrix, Quantity: 1},
			{ItemID: ItemGravityMatrix, Quantity: 1},
			{ItemID: ItemAntimatter, Quantity: 1},
		},
		Outputs:       []ItemAmount{{ItemID: ItemUniverseMatrix, Quantity: 1}},
		Duration:      150,
		EnergyCost:    10,
		BuildingTypes: []BuildingType{BuildingTypeMatrixLab, BuildingTypeSelfEvolutionLab},
		TechUnlock:    []string{"universe_matrix"},
	},
	"ammo_bullet": {
		ID:            "ammo_bullet",
		Name:          "Bullet",
		Inputs:        []ItemAmount{{ItemID: ItemIronIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemAmmoBullet, Quantity: 5}},
		Duration:      20,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"weapon_system"},
	},
	"ammo_missile": {
		ID:            "ammo_missile",
		Name:          "Missile",
		Inputs:        []ItemAmount{{ItemID: ItemTitaniumIngot, Quantity: 2}, {ItemID: ItemProcessor, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemAmmoMissile, Quantity: 1}},
		Duration:      80,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"missile_turret"},
	},
	"plasma_capsule": {
		ID:   "plasma_capsule",
		Name: "等离子胶囊",
		Inputs: []ItemAmount{
			{ItemID: ItemTitaniumAlloy, Quantity: 1},
			{ItemID: ItemParticleContainer, Quantity: 1},
			{ItemID: ItemHydrogen, Quantity: 2},
		},
		Outputs:       []ItemAmount{{ItemID: ItemPlasmaCapsule, Quantity: 1}},
		Duration:      60,
		EnergyCost:    4,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"plasma_turret"},
	},
	"antimatter_capsule": {
		ID:   "antimatter_capsule",
		Name: "Antimatter Capsule",
		Inputs: []ItemAmount{
			{ItemID: ItemAntimatter, Quantity: 2},
			{ItemID: ItemAnnihilationConstraintSphere, Quantity: 1},
			{ItemID: ItemTitaniumAlloy, Quantity: 1},
		},
		Outputs:       []ItemAmount{{ItemID: ItemAntimatterCapsule, Quantity: 1}},
		Duration:      120,
		EnergyCost:    8,
		BuildingTypes: []BuildingType{BuildingTypeRecomposingAssembler},
		TechUnlock:    []string{"mass_energy_storage"},
	},
	"gravity_missile": {
		ID:   "gravity_missile",
		Name: "Gravity Missile",
		Inputs: []ItemAmount{
			{ItemID: ItemAmmoMissile, Quantity: 1},
			{ItemID: ItemStrangeMatter, Quantity: 1},
			{ItemID: ItemGravityMatrix, Quantity: 1},
		},
		Outputs:       []ItemAmount{{ItemID: ItemGravityMissile, Quantity: 1}},
		Duration:      120,
		EnergyCost:    8,
		BuildingTypes: []BuildingType{BuildingTypeRecomposingAssembler},
		TechUnlock:    []string{"gravity_missile"},
	},
	"prototype": {
		ID:   "prototype",
		Name: "Prototype Payload",
		Inputs: []ItemAmount{
			{ItemID: ItemCircuitBoard, Quantity: 2},
			{ItemID: ItemProcessor, Quantity: 1},
			{ItemID: ItemTitaniumAlloy, Quantity: 1},
		},
		Outputs:       []ItemAmount{{ItemID: ItemPrototype, Quantity: 1}},
		Duration:      90,
		EnergyCost:    4,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"prototype"},
	},
	"precision_drone": {
		ID:   "precision_drone",
		Name: "Precision Drone Payload",
		Inputs: []ItemAmount{
			{ItemID: ItemPrototype, Quantity: 1},
			{ItemID: ItemQuantumChip, Quantity: 1},
			{ItemID: ItemDeuteriumFuelRod, Quantity: 1},
		},
		Outputs:       []ItemAmount{{ItemID: ItemPrecisionDrone, Quantity: 1}},
		Duration:      120,
		EnergyCost:    6,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"precision_drone"},
	},
	"corvette": {
		ID:   "corvette",
		Name: "Corvette Hull Payload",
		Inputs: []ItemAmount{
			{ItemID: ItemPrecisionDrone, Quantity: 2},
			{ItemID: ItemFrameMaterial, Quantity: 2},
			{ItemID: ItemQuantumChip, Quantity: 1},
			{ItemID: ItemDeuteriumFuelRod, Quantity: 1},
		},
		Outputs:       []ItemAmount{{ItemID: ItemCorvette, Quantity: 1}},
		Duration:      180,
		EnergyCost:    10,
		BuildingTypes: []BuildingType{BuildingTypeRecomposingAssembler},
		TechUnlock:    []string{"corvette"},
	},
	"destroyer": {
		ID:   "destroyer",
		Name: "Destroyer Hull Payload",
		Inputs: []ItemAmount{
			{ItemID: ItemCorvette, Quantity: 1},
			{ItemID: ItemFrameMaterial, Quantity: 4},
			{ItemID: ItemQuantumChip, Quantity: 2},
			{ItemID: ItemDeuteriumFuelRod, Quantity: 2},
			{ItemID: ItemTitaniumAlloy, Quantity: 2},
		},
		Outputs:       []ItemAmount{{ItemID: ItemDestroyer, Quantity: 1}},
		Duration:      240,
		EnergyCost:    12,
		BuildingTypes: []BuildingType{BuildingTypeRecomposingAssembler},
		TechUnlock:    []string{"destroyer"},
	},
	"solar_sail": {
		ID:            "solar_sail",
		Name:          "Solar Sail",
		Inputs:        []ItemAmount{{ItemID: ItemGraphene, Quantity: 2}, {ItemID: ItemCarbonNanotube, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemSolarSail, Quantity: 1}},
		Duration:      30,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"solar_sail_orbit"},
	},
	"glass": {
		HandcraftAllowed: true,
		ID:               "glass",
		Name:             "Glass",
		Inputs:           []ItemAmount{{ItemID: ItemStoneOre, Quantity: 2}},
		Outputs:          []ItemAmount{{ItemID: ItemGlass, Quantity: 1}},
		Duration:         50,
		EnergyCost:       1,
		BuildingTypes:    []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:       []string{"automatic_metallurgy"},
	},
	"steel": {
		HandcraftAllowed: true,
		ID:               "steel",
		Name:             "Steel",
		Inputs:           []ItemAmount{{ItemID: ItemIronIngot, Quantity: 3}},
		Outputs:          []ItemAmount{{ItemID: ItemSteel, Quantity: 1}},
		Duration:         60,
		EnergyCost:       1,
		BuildingTypes:    []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:       []string{"steel_smelting"},
	},
	"silicon_ore": {
		ID:            "silicon_ore",
		Name:          "Silicon Ore From Stone",
		Inputs:        []ItemAmount{{ItemID: ItemStoneOre, Quantity: 10}},
		Outputs:       []ItemAmount{{ItemID: ItemSiliconOre, Quantity: 1}},
		Duration:      60,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:    []string{"smelting_purification"},
	},
	"diamond": {
		ID:            "diamond",
		Name:          "Diamond",
		Inputs:        []ItemAmount{{ItemID: ItemEnergeticGraphite, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemDiamond, Quantity: 1}},
		Duration:      80,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:    []string{"crystal_smelting"},
	},
	"crystal": {
		ID:            "crystal",
		Name:          "Crystal Silicon",
		Inputs:        []ItemAmount{{ItemID: ItemSiliconIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemCrystalSilicon, Quantity: 1}},
		Duration:      80,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeArcSmelter, BuildingTypePlaneSmelter, BuildingTypeNegentropySmelter},
		TechUnlock:    []string{"crystal_smelting"},
	},
	"organic_crystal": {
		ID:            "organic_crystal",
		Name:          "Organic Crystal",
		Inputs:        []ItemAmount{{ItemID: ItemPlastic, Quantity: 2}, {ItemID: ItemRefinedOil, Quantity: 1}, {ItemID: ItemWater, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemOrganicCrystal, Quantity: 1}},
		Duration:      80,
		EnergyCost:    2,
		BuildingTypes: []BuildingType{BuildingTypeChemicalPlant, BuildingTypeQuantumChemicalPlant},
		TechUnlock:    []string{"polymer_chemical"},
	},
	"prism": {
		HandcraftAllowed: true,
		ID:               "prism",
		Name:             "Prism",
		Inputs:           []ItemAmount{{ItemID: ItemGlass, Quantity: 3}},
		Outputs:          []ItemAmount{{ItemID: ItemPrism, Quantity: 2}},
		Duration:         40,
		BuildingTypes:    []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:       []string{"plasma_control"},
	},
	"plasma_exciter": {
		ID:            "plasma_exciter",
		Name:          "Plasma Exciter",
		Inputs:        []ItemAmount{{ItemID: ItemMagneticCoil, Quantity: 4}, {ItemID: ItemPrism, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemPlasmaExciter, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"plasma_control"},
	},
	"engine": {
		ID:            "engine",
		Name:          "Engine",
		Inputs:        []ItemAmount{{ItemID: ItemMotor, Quantity: 2}, {ItemID: ItemMagneticCoil, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemEngine, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"engine"},
	},
	"electromagnetic_turbine": {
		ID:            "electromagnetic_turbine",
		Name:          "Electromagnetic Turbine",
		Inputs:        []ItemAmount{{ItemID: ItemMotor, Quantity: 2}, {ItemID: ItemMagneticCoil, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemElectromagneticTurbine, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"magnetic_levitation"},
	},
	"super_magnetic_ring": {
		ID:            "super_magnetic_ring",
		Name:          "Super-Magnetic Ring",
		Inputs:        []ItemAmount{{ItemID: ItemElectromagneticTurbine, Quantity: 2}, {ItemID: ItemMagnet, Quantity: 3}, {ItemID: ItemEnergeticGraphite, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemSuperMagneticRing, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"super_magnetic"},
	},
	"particle_container": {
		ID:            "particle_container",
		Name:          "Particle Container",
		Inputs:        []ItemAmount{{ItemID: ItemElectromagneticTurbine, Quantity: 2}, {ItemID: ItemGraphene, Quantity: 2}, {ItemID: ItemCopperIngot, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemParticleContainer, Quantity: 1}},
		Duration:      60,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"particle_container"},
	},
	"proliferator_mk1": {
		HandcraftAllowed: true,
		ID:               "proliferator_mk1",
		Name:             "Proliferator Mk.I",
		Inputs:           []ItemAmount{{ItemID: ItemCoal, Quantity: 2}},
		Outputs:          []ItemAmount{{ItemID: ItemProliferatorMk1, Quantity: 1}},
		Duration:         20,
		BuildingTypes:    []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:       []string{"proliferator_mk1"},
	},
	"proliferator_mk2": {
		ID:            "proliferator_mk2",
		Name:          "Proliferator Mk.II",
		Inputs:        []ItemAmount{{ItemID: ItemProliferatorMk1, Quantity: 2}, {ItemID: ItemDiamond, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemProliferatorMk2, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"proliferator_mk2"},
	},
	"combustible_unit": {
		HandcraftAllowed: true,
		ID:               "combustible_unit",
		Name:             "Combustible Unit",
		Inputs:           []ItemAmount{{ItemID: ItemCoal, Quantity: 3}},
		Outputs:          []ItemAmount{{ItemID: ItemCombustibleUnit, Quantity: 1}},
		Duration:         20,
		BuildingTypes:    []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:       []string{"combustible_unit"},
	},
	"shell_set": {
		ID:            "shell_set",
		Name:          "Shell Set",
		Inputs:        []ItemAmount{{ItemID: ItemCombustibleUnit, Quantity: 2}, {ItemID: ItemCopperIngot, Quantity: 2}},
		Outputs:       []ItemAmount{{ItemID: ItemShellSet, Quantity: 1}},
		Duration:      40,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"implosion_cannon"},
	},
	"titanium_ammo": {
		ID:            "titanium_ammo",
		Name:          "Titanium Ammo Box",
		Inputs:        []ItemAmount{{ItemID: ItemAmmoBullet, Quantity: 1}, {ItemID: ItemTitaniumIngot, Quantity: 1}},
		Outputs:       []ItemAmount{{ItemID: ItemTitaniumAmmo, Quantity: 1}},
		Duration:      30,
		BuildingTypes: []BuildingType{BuildingTypeAssemblingMachineMk1, BuildingTypeAssemblingMachineMk2, BuildingTypeAssemblingMachineMk3},
		TechUnlock:    []string{"titanium_ammo"},
	},
}

// Recipe returns a recipe definition by id.
func Recipe(id string) (RecipeDefinition, bool) {
	def, ok := recipeCatalog[id]
	return def, ok
}

// AllRecipes returns a copy of recipes for read-only usage.
func AllRecipes() []RecipeDefinition {
	recipes := make([]RecipeDefinition, 0, len(recipeCatalog))
	for _, def := range recipeCatalog {
		recipes = append(recipes, def)
	}
	return recipes
}
