import {
  ALL_EVENT_TYPES,
  DEFAULT_EVENT_TYPES,
  DEFAULT_GALAXY_ID,
  DEFAULT_PLANET_ID,
  DEFAULT_PLAYERS,
  DEFAULT_SERVER_URL,
  DEFAULT_SSE_BUFFER_SIZE,
  DEFAULT_SSE_SILENT_EVENT_TYPES,
  DEFAULT_SYSTEM_ID,
} from '../../shared-client/src/config.js';

export {
  ALL_EVENT_TYPES,
  DEFAULT_EVENT_TYPES,
  DEFAULT_GALAXY_ID,
  DEFAULT_PLANET_ID,
  DEFAULT_PLAYERS,
  DEFAULT_SYSTEM_ID,
};

export const SERVER_URL = process.env.SW_SERVER ?? DEFAULT_SERVER_URL;
export const AGENT_GATEWAY_URL = process.env.SW_AGENT_GATEWAY ?? 'http://127.0.0.1:18180';
export function getAgentGatewayUrl() {
  return process.env.SW_AGENT_GATEWAY ?? AGENT_GATEWAY_URL;
}
export const SSE_BUFFER_SIZE = DEFAULT_SSE_BUFFER_SIZE;
export const SSE_VERBOSE = process.env.SW_SSE_VERBOSE === '1';
export const SSE_SILENT_EVENT_TYPES = DEFAULT_SSE_SILENT_EVENT_TYPES;
