import chalk from 'chalk';

import type { ApiClient } from '../api.js';
import { fmtError } from './format.js';
import type { CommandContext } from './game-commands.js';

const HELP_ENTRIES: Record<string, { usage?: string; desc: string }> = {
  configure_distributor: { usage: '<id> <item_id|none> <none|supply|demand> <local_storage> [--delivery true|false] [--collection true|false]', desc: '配置仓库配送器；省略开关保留原值' },
  install_logistics_bot: { usage: '<id> <quantity> [--source player|storage]', desc: '消耗背包或绑定仓库的机器人安装至配送器' },
  uninstall_logistics_bot: { usage: '<id> <quantity>', desc: '回收空载停靠的配送机器人至背包' },
  configure_mecha_logistics: { usage: '<unit_id> <item:min:max,...|none>', desc: '替换机甲配送请求，最多 8 项，none 清空' },
  health: { desc: 'Server status and current tick' },
  metrics: { desc: 'Runtime metrics' },
  summary: { desc: 'Game summary (resources, players, map)' },
  stats: { desc: 'Current player statistics' },
  briefing: { usage: '[alert_limit]', desc: 'One-shot agent briefing (self/war/fleets/alerts/commands)' },
  catalog_commands: { desc: 'Public command structure catalog (GET /catalog/commands)' },
  galaxy: { desc: 'Galaxy list' },
  system: { usage: '[system_id]', desc: 'System details (default: sys-1)' },
  system_runtime: { usage: '[system_id]', desc: 'System runtime state including fleets, contacts, blockades and battle reports' },
  planet: { usage: '[planet_id]', desc: 'Planet summary (default: planet-1-1)' },
  planet_runtime: { usage: '[planet_id]', desc: 'Planet runtime state including contacts, frontlines and ground task forces' },
  blueprints: { usage: '[blueprint_id]', desc: 'List player warfare blueprints or inspect one blueprint in detail' },
  war_industry: { desc: 'Military production, refit, deployment hub and supply node status' },
  task_forces: { desc: 'Player-owned task force list with supply and command capacity' },
  theaters: { desc: 'Player-owned theater zones and objectives' },
  scene: { usage: '[planet_id] <x> <y> <width> <height> [--near_x X --near_y Y --radius R]', desc: 'Cube-sphere atlas scene and seam patches' },
  inspect: { usage: '<planet_id> <building|unit|resource|sector> <entity_id>', desc: 'Planet inspect raw JSON' },
  fleet_status: { usage: '[fleet_id]', desc: 'Fleet list or one fleet detail' },
  fog: { usage: '[planet_id] [x y width height]', desc: 'ASCII fog slice via /scene (default: 0 0 32 16)' },
  scan_galaxy: { usage: '[galaxy_id]', desc: '登记星系到星图（不改地表迷雾）' },
  scan_system: { usage: '<system_id>', desc: '登记恒星系到星图（不改地表迷雾）' },
  scan_planet: { usage: '<planet_id>', desc: '登记星球到星图（不改地表迷雾）' },
  build: { usage: '<x> <y> <type> [--z <z>] [--direction <dir>] [--recipe <id>]', desc: 'Build any server-side buildable structure' },
  move: { usage: '<entity_id> <x> <y> [--z <z>]', desc: 'Move entity to position' },
  attack: { usage: '<entity_id> <target_id>', desc: 'Attack target entity' },
  order: { usage: '<entity_id[,entity_id...]> <attack_move|patrol|guard|hold|follow|retreat|stop> [x y] [--target <entity_id>] [--planet <planet_id>]', desc: 'R5 部队指令：攻击移动/巡逻/守卫/坚守/跟随/撤退/停止（支持逗号分隔批量；--planet 跨行星同 ID 消歧）' },
  produce: { usage: '<entity_id> <unit_type> [--planet <planet_id>]', desc: 'Produce a server-public world unit（按建筑所在行星结算）' },
  upgrade: { usage: '<entity_id> [--planet <planet_id>]', desc: 'Upgrade building（按建筑所在行星结算）' },
  demolish: { usage: '<entity_id> [--planet <planet_id>]', desc: 'Demolish building（按建筑所在行星结算）' },
  install_logistics_vehicle: { usage: '<station_id> <logistics_drone|logistics_vessel> <quantity> [--source player|station]', desc: '消耗背包或站内成品安装运输器，受站点槽位上限限制' },
  configure_logistics_station: { usage: '<building_id> [--drone-capacity <n>] [--input-priority <n>] [--output-priority <n>] [--interstellar-enabled <true|false>] [--warp-enabled <true|false>] [--ship-slots <n>] [--belt-ports direction:input|output:item_id,...|none]', desc: 'Configure logistics station capacity, priority and interstellar switches' },
  configure_logistics_slot: { usage: '<building_id> <planetary|interstellar> <item_id> [<none|supply|demand|both> <local_storage> | --remove]', desc: '配置物流物品槽；remove移除无库存、无端口或在途引用的空槽' },
  cancel_construction: { usage: '<task_id>', desc: 'Cancel queued or running construction task' },
  restore_construction: { usage: '<task_id>', desc: 'Restore a cancelled construction task' },
  start_research: { usage: '<tech_id>', desc: 'Start researching a technology' },
  cancel_research: { usage: '<tech_id>', desc: 'Cancel a technology in progress or queue' },
  set_recipe: { usage: '<entity_id> [recipe_id] [--planet <planet_id>]', desc: '原地切换生产建筑/研究站配方；省略 recipe_id 时研究站回研究模式、生产建筑转空闲，切换后进度清零、库存保留' },
  set_energy_exchanger_mode: { usage: '<building_id> <charge|discharge|standby> [--planet <planet_id>]', desc: '切换蓄电器能量枢纽模式：charge 电网盈余充蓄电池，discharge 放电回电网，standby 不转换' },
  blueprint_create: { usage: '<blueprint_id> <ground|space> [--name <name>] (--base-frame <base_frame_id> | --base-hull <base_hull_id>)', desc: 'Create a draft warfare blueprint' },
  blueprint_set_component: { usage: '<blueprint_id> <slot_id> <component_id>', desc: 'Set one component on a draft or validated warfare blueprint' },
  blueprint_validate: { usage: '<blueprint_id>', desc: 'Validate a warfare blueprint and receive structured legality issues' },
  blueprint_finalize: { usage: '<blueprint_id> [--target-state <state>]', desc: 'Advance a warfare blueprint to the next or chosen lifecycle state' },
  blueprint_variant: { usage: '<parent_blueprint_id> <blueprint_id> <allowed_slot_ids_csv> [--name <name>]', desc: 'Create a controlled variant from a preset or player blueprint' },
  queue_military_production: { usage: '<building_id> <deployment_hub_id> <blueprint_id> [--count <n>]', desc: 'Queue military production and deliver ready payloads into a deployment hub' },
  refit_unit: { usage: '<building_id> <unit_id> <target_blueprint_id>', desc: 'Send a squad or fleet into authoritative refit' },
  deploy_squad: { usage: '<building_id> <blueprint_id> [--count <n>] [--planet <planet_id>]', desc: 'Consume a squad payload from a hub and create a combat squad' },
  commission_fleet: { usage: '<building_id> <blueprint_id> <system_id> [--count <n>] [--fleet-id <fleet_id>]', desc: 'Consume a fleet payload from a hub and create or reinforce a fleet' },
  fleet_assign: { usage: '<fleet_id> <line|vee|circle|wedge>', desc: 'Change a fleet formation' },
  fleet_attack: { usage: '<fleet_id> <planet_id> <target_id>', desc: 'Order a fleet to attack a target in the same system' },
  fleet_disband: { usage: '<fleet_id>', desc: 'Disband a fleet and remove it from runtime' },
  fleet_move: { usage: '<fleet_id> <target_system_id>', desc: 'Order a fleet to transit to a connected star system' },
  task_force_create: { usage: '<task_force_id> [--name <name>] [--stance <stance>]', desc: 'Create a task force shell for squads and fleets' },
  task_force_assign: { usage: '<task_force_id> <squad|fleet> <member_ids_csv> [--system <system_id>] [--planet <planet_id>]', desc: 'Assign one or more squads or fleets into a task force' },
  task_force_set_stance: { usage: '<task_force_id> <stance>', desc: 'Change task force doctrine and engagement posture' },
  task_force_deploy: { usage: '<task_force_id> [--theater <theater_id>] [--system <system_id>] [--planet <planet_id>] [--x <x> --y <y> [--z <z>]] [--frontline <frontline_id>] [--ground-order <order>] [--support-mode <mode>]', desc: 'Set task force deployment intent, frontline order and orbital support mode' },
  theater_create: { usage: '<theater_id> [--name <name>]', desc: 'Create a theater container for war zoning and objectives' },
  theater_define_zone: { usage: '<theater_id> <zone_type> [--system <system_id>] [--planet <planet_id>] [--x <x> --y <y> [--z <z>]] [--radius <n>]', desc: 'Define or update one theater zone' },
  theater_set_objective: { usage: '<theater_id> <objective_type> [--system <system_id>] [--planet <planet_id>] [--entity <entity_id>] [--description <text>]', desc: 'Set a theater objective anchor and description' },
  blockade_planet: { usage: '<task_force_id> <planet_id>', desc: 'Issue a blockade intent against one planet' },
  transfer: { usage: '<building_id> <item_id> <quantity> [--planet <planet_id>]', desc: 'Load items from player inventory into building local storage（按建筑所在行星结算）' },
  mine_resource: { usage: '<executor_id> <resource_id> <quantity> [--planet <planet_id>]', desc: '手动采集固体资源到背包（按执行体所在行星结算）' },
  craft_item: { usage: '<executor_id> <recipe_id> <quantity> [--planet <planet_id>]', desc: '使用背包原料进行个人制造，quantity为批数（按执行体所在行星结算）' },
  configure_traffic_monitor: { usage: '<building_id> <belt_id|none> --window <1..600> --minimum <0..60> --alerts <on|off>', desc: '监测相邻皮带真实流出量；none 清绑定，配置重置采样' },
  form_squad: { usage: '<entity_id...> [--name <name>] [--planet <id>]', desc: '选中单位编成军团（可含补给车）' },
  squad_order: { usage: '<squad_id> <attack|defend|retreat|resupply> [<x> <y>] [--planet <id>]', desc: '军团指令；resupply 自动前往最近补给站' },
  dissolve_squad: { usage: '<squad_id> [--planet <id>]', desc: '解散军团，单位保留当前指令' },
  set_rally_point:{usage:'<building_id> <x> <y> [--planet <id>]',desc:'设置出厂单位集结点'},
  configure_sorter: { usage: '<building_id> --inputs west --outputs east [--mode allow|deny] [--items iron_ore] [--planet <id>]', desc: '设置分拣器方向和物品过滤' },
  configure_splitter: { usage: '<building_id> --inputs west --outputs east,south,north [--input-priority west] [--output-priority east] [--filters east:iron_ore,south:copper_ore]', desc: '完整替换分流器端口、优先级和物品过滤；省略可选项即清除' },
  cancel_mecha_job: { usage: '<executor_id> [--planet <planet_id>]', desc: '取消机甲任务并返还未完成批次原料' },
  refuel_mecha: { usage: '<executor_id> <fuel_item_id> [count] [--planet <planet_id>]', desc: 'Refuel an executor mecha: burn up to count fuel items (default 1) until the core is full' },
  switch_active_planet: { usage: '<planet_id>', desc: '切换自己的视图焦点/默认落点行星（不影响其他玩家；所有已加载行星始终结算）' },
  set_ray_receiver_mode: { usage: '<building_id> <power|photon|hybrid> [--planet <planet_id>]', desc: 'Switch ray receiver mode（按建筑所在行星结算）' },
  launch_rocket: { usage: '<building_id> <system_id> [--layer <n>] [--count <n>] [--planet <planet_id>]', desc: 'Launch loaded rockets from a Vertical Launching Silo into a Dyson layer' },
  launch_solar_sail: { usage: '<building_id> [--count <n>] [--orbit-radius <n>] [--inclination <n>] [--planet <planet_id>]', desc: 'Launch loaded solar sails from an EM Rail Ejector' },
  build_dyson_node: { usage: '<system_id> <layer_index> <latitude> <longitude> [--orbit-radius <n>]', desc: 'Build a Dyson sphere node' },
  build_dyson_frame: { usage: '<system_id> <layer_index> <node_a_id> <node_b_id>', desc: 'Build a Dyson sphere frame' },
  build_dyson_shell: { usage: '<system_id> <layer_index> <latitude_min> <latitude_max> <coverage>', desc: 'Build a Dyson sphere shell' },
  demolish_dyson: { usage: '<system_id> <node|frame|shell> <component_id>', desc: 'Demolish a Dyson sphere component' },
  agent_list: { desc: 'List agent-gateway agent profiles' },
  agent_create: { usage: '<name> --provider <provider_id> [--role <worker|manager|director>] [--can-create-agents <true|false>] [--command-categories <csv>] [--planet-ids <csv>] [--dispatch-agent-ids <csv>] [--direct-message-agent-ids <csv>]', desc: 'Create an agent-gateway agent profile bound to the current player key' },
  agent_update: { usage: '<agent_id> [--role <worker|manager|director>] [--can-create-agents <true|false>] [--command-categories <csv>] [--planet-ids <csv>] [--dispatch-agent-ids <csv>] [--direct-message-agent-ids <csv>]', desc: 'Patch agent-gateway agent policy or role' },
  agent_message: { usage: '<agent_id> <content>', desc: 'Send one direct task message to an agent thread' },
  agent_thread: { usage: '<agent_id>', desc: 'Inspect one agent thread including messages, tool calls and logs' },
  raw: { usage: '<json>', desc: 'Send raw /commands request JSON' },
  switch: { usage: '[player_id] [key]', desc: 'Switch player' },
  events: { usage: '[count]', desc: 'Show recent SSE events (default: 10)' },
  status: { desc: 'Current player and connection status' },
  audit: { usage: '[options]', desc: 'Query audit log' },
  event_snapshot: { usage: '[options]', desc: 'Query event snapshot' },
  alert_snapshot: { usage: '[options]', desc: 'Query production alert snapshot' },
  save: { usage: '[--reason <text>]', desc: 'Trigger manual save' },
  replay: { usage: '[options]', desc: 'Replay tick range' },
  rollback: { usage: '[options]', desc: 'Rollback to tick' },
  help: { usage: '[command]', desc: 'Show help' },
  clear: { desc: 'Clear screen' },
  quit: { desc: 'Exit' },
};

const HELP_TEXT = [
  chalk.bold('Commands:'),
  '',
  chalk.bold('  Query:'),
  '    health          Server status and current tick',
  '    metrics         Runtime metrics',
  '    summary         Game summary',
  '    stats           Current player statistics',
  '    briefing [n]    Agent briefing snapshot',
  '    catalog_commands  Public command structure catalog',
  '    galaxy          Galaxy list',
  '    system [id]     System details',
  '    system_runtime [id]  System runtime with fleets, contacts and battle reports',
  '    planet [id]     Planet summary',
  '    planet_runtime [id]  Planet runtime with contacts and frontlines',
  '    blueprints [id] List warfare blueprints or inspect one blueprint',
  '    war_industry    Military production, refit and supply nodes',
  '    task_forces     Task force status, members and supply',
  '    theaters        Theater zones and objectives',
  '    scene [id] <x> <y> <w> <h>',
  '    inspect <planet_id> <kind> <entity_id>',
  '    fleet_status [id]    Fleet list or one fleet detail',
  '    fog [id] [x y w h]  ASCII fog slice',
  '',
  chalk.bold('  Discovery:'),
  '    scan_galaxy [id]   登记星系到星图（不改地表迷雾）',
  '    scan_system <id>   登记恒星系到星图（不改地表迷雾）',
  '    scan_planet <id>   登记星球到星图（不改地表迷雾）',
  '',
  chalk.bold('  Game Actions:'),
  '    configure_distributor <id> <item_id|none> <none|supply|demand> <local_storage> [--delivery true|false] [--collection true|false]',
  '    install_logistics_bot <id> <quantity> [--source player|storage]',
  '    uninstall_logistics_bot <id> <quantity>',
  '    configure_mecha_logistics <unit_id> <item:min:max,...|none> [--planet <id>]',
  '    build <x> <y> <type> [--z <z>] [--direction <dir>] [--recipe <id>] [--planet <id>]',
  '    move <entity_id> <x> <y> [--z <z>] [--planet <id>]',
  '    attack <entity_id> <target> [--planet <id>]',
  '    order <entity_id[,id...]> <attack_move|patrol|guard|hold|follow|retreat|stop> [x y] [--target <id>] [--planet <id>]',
  '    produce <entity_id> <type> [--planet <id>]',
  '    upgrade <entity_id> [--planet <id>]',
  '    demolish <entity_id> [--planet <id>]',
  '    configure_traffic_monitor <building_id> <belt_id|none> --window <1..600> --minimum <0..60> --alerts <on|off>',
  '    configure_splitter <building_id> --inputs west --outputs east,south [--input-priority west] [--output-priority east] [--filters east:iron_ore]',
  '    configure_logistics_station <building_id> [--drone-capacity <n>] [--input-priority <n>] [--output-priority <n>] [--interstellar-enabled <true|false>] [--warp-enabled <true|false>] [--ship-slots <n>] [--belt-ports direction:input|output:item_id,...|none]',
  '    configure_logistics_slot <building_id> <planetary|interstellar> <item_id> <none|supply|demand|both> <local_storage>',
  '    cancel_construction <task_id>',
  '    restore_construction <task_id>',
  '    start_research <tech_id>',
  '    cancel_research <tech_id>',
  '    set_recipe <entity_id> [recipe_id]',
  '    set_energy_exchanger_mode <building_id> <charge|discharge|standby>',
  '    blueprint_create <blueprint_id> <ground|space> [--name <name>] (--base-frame <base_frame_id> | --base-hull <base_hull_id>)',
  '    blueprint_set_component <blueprint_id> <slot_id> <component_id>',
  '    blueprint_validate <blueprint_id>',
  '    blueprint_finalize <blueprint_id> [--target-state <state>]',
  '    blueprint_variant <parent_blueprint_id> <blueprint_id> <allowed_slot_ids_csv> [--name <name>]',
  '    queue_military_production <building_id> <deployment_hub_id> <blueprint_id> [--count <n>]',
  '    refit_unit <building_id> <unit_id> <target_blueprint_id>',
  '    deploy_squad <building_id> <blueprint_id> [--count <n>] [--planet <planet_id>]',
  '    form_squad <entity_id...> [--name <name>] [--planet <id>]',
  '    squad_order <squad_id> <attack|defend|retreat|resupply> [<x> <y>] [--planet <id>]',
  '    dissolve_squad <squad_id> [--planet <id>]',
  '    commission_fleet <building_id> <blueprint_id> <system_id> [--count <n>] [--fleet-id <fleet_id>]',
  '    fleet_assign <fleet_id> <line|vee|circle|wedge>',
  '    fleet_attack <fleet_id> <planet_id> <target_id>',
  '    fleet_disband <fleet_id>',
  '    fleet_move <fleet_id> <target_system_id>',
  '    task_force_create <task_force_id> [--name <name>] [--stance <stance>]',
  '    task_force_assign <task_force_id> <squad|fleet> <member_ids_csv> [--system <system_id>] [--planet <planet_id>]',
  '    task_force_set_stance <task_force_id> <stance>',
  '    task_force_deploy <task_force_id> [--theater <theater_id>] [--system <system_id>] [--planet <planet_id>] [--x <x> --y <y> [--z <z>]] [--frontline <frontline_id>] [--ground-order <order>] [--support-mode <mode>]',
  '    theater_create <theater_id> [--name <name>]',
  '    theater_define_zone <theater_id> <zone_type> [--system <system_id>] [--planet <planet_id>] [--x <x> --y <y> [--z <z>]] [--radius <n>]',
  '    theater_set_objective <theater_id> <objective_type> [--system <system_id>] [--planet <planet_id>] [--entity <entity_id>] [--description <text>]',
  '    blockade_planet <task_force_id> <planet_id>',
  '    transfer <building_id> <item_id> <quantity>',
  '    mine_resource <executor_id> <resource_id> <quantity>',
  '    craft_item <executor_id> <recipe_id> <quantity>',
  '    cancel_mecha_job <executor_id>',
  '    refuel_mecha <executor_id> <fuel_item_id> [count]',
  '    switch_active_planet <planet_id>',
  '    set_ray_receiver_mode <building_id> <power|photon|hybrid>',
  '    launch_rocket <building_id> <system_id> [--layer <n>] [--count <n>]',
  '    launch_solar_sail <building_id> [--count <n>] [--orbit-radius <n>] [--inclination <n>]',
  '    build_dyson_node <system_id> <layer_index> <latitude> <longitude> [--orbit-radius <n>]',
  '    build_dyson_frame <system_id> <layer_index> <node_a_id> <node_b_id>',
  '    build_dyson_shell <system_id> <layer_index> <latitude_min> <latitude_max> <coverage>',
  '    demolish_dyson <system_id> <node|frame|shell> <component_id>',
  '',
  chalk.bold('  Agent Gateway:'),
  '    agent_list',
  '    agent_create <name> --provider <provider_id> [--role <worker|manager|director>] [--can-create-agents <true|false>] [--command-categories <csv>] [--planet-ids <csv>] [--dispatch-agent-ids <csv>] [--direct-message-agent-ids <csv>]',
  '    agent_update <agent_id> [--role <worker|manager|director>] [--can-create-agents <true|false>] [--command-categories <csv>] [--planet-ids <csv>] [--dispatch-agent-ids <csv>] [--direct-message-agent-ids <csv>]',
  '    agent_message <agent_id> <content>',
  '    agent_thread <agent_id>',
  '',
  chalk.bold('  Admin/Debug:'),
  '    audit [options]             Query audit log',
  '    event_snapshot [options]    Query event snapshot',
  '    alert_snapshot [options]    Query production alert snapshot',
  '    save [--reason <text>]     Trigger manual save',
  '    replay [options]            Replay tick range',
  '    rollback [options]          Rollback to tick',
  '    raw <json>                  Send raw /commands request JSON',
  '',
  chalk.bold('  Util:'),
  '    switch [player_id] [key]  Switch player',
  '    events [count]            Show recent SSE events',
  '    status                    Current player & server',
  '    help [command]            Show help',
  '    clear                     Clear screen',
  '    quit / exit               Exit',
].join('\n');

async function getProduceHelp(api: ApiClient): Promise<string> {
  const usage = '<entity_id> <unit_type>';
  try {
    const catalog = await api.fetchCatalog();
    const units = (catalog.world_units ?? [])
      .filter((entry) => entry.public && entry.production_mode === 'world_produce' && entry.runtime_class === 'world_unit')
      .map((entry) => entry.id);
    if (units.length > 0) {
      return `${chalk.bold('produce')} ${chalk.dim(usage)}\n  Produce a server-public world unit from /catalog.world_units: ${units.join(', ')}`;
    }
  } catch {
    // Fall back to generic help when the server is unavailable.
  }
  return `${chalk.bold('produce')} ${chalk.dim(usage)}\n  Produce a server-public world unit; available ids come from /catalog.world_units when the server is reachable`;
}

function getCommandHelp(cmd: string, api: ApiClient): string | Promise<string> {
  const entry = HELP_ENTRIES[cmd];
  if (!entry) {
    return fmtError(`Unknown command: ${cmd}`);
  }
  if (cmd === 'produce') {
    return getProduceHelp(api);
  }
  return `${chalk.bold(cmd)} ${chalk.dim(entry.usage ?? '')}\n  ${entry.desc}`;
}

export function cmdHelp(args: string[], { api }: CommandContext): string | Promise<string> {
  if (args[0]) {
    return getCommandHelp(args[0], api);
  }
  return HELP_TEXT;
}
