import { useEffect, useState } from 'react';
import type { Building, CatalogView, CommandResponse, DistributorConfig, ItemInventory, PlanetRuntimeView } from '@shared/types';
import { useApiClient } from '@/hooks/use-api-client';
import { submitPlanetCommand } from '@/features/planet-commands/executor';
import { PLANET_COMMAND_RECOVERY_EVENT_TYPES } from '@/features/planet-commands/store';
import { getItemDisplayName } from './model';

const phase: Record<string, string> = { idle: '停靠', takeoff: '起飞', in_flight: '配送中', landing: '降落', waiting_unload: '等待卸货', stranded: '基地失效' };
export function DistributorControls({ building, host, runtime, catalog, planetId, canControl, inventory }: { building: Building; host?: Building; runtime?: PlanetRuntimeView; catalog?: CatalogView; planetId: string; canControl: boolean; inventory?: ItemInventory }) {
  const client = useApiClient();
  const live = runtime?.logistics_distributors?.find(entry => entry.building_id === building.id);
  const state = live?.state ?? building.distributor!;
  const [config, setConfig] = useState<DistributorConfig>({ item_id: state.item_id, mode: state.mode, local_storage: state.local_storage, player_delivery_enabled: state.player_delivery_enabled, player_collection_enabled: state.player_collection_enabled });
  const [source, setSource] = useState<'player' | 'storage'>('player'), [count, setCount] = useState(1), [pending, setPending] = useState(false);
  useEffect(() => setConfig({ item_id: state.item_id, mode: state.mode, local_storage: state.local_storage, player_delivery_enabled: state.player_delivery_enabled, player_collection_enabled: state.player_collection_enabled }), [building.id, state.item_id, state.mode, state.local_storage, state.player_delivery_enabled, state.player_collection_enabled]);
  const bots = (runtime?.logistics_bots ?? []).filter(b => b.distributor_id === building.id), idle = bots.filter(b => b.status === 'idle' && !Object.values(b.cargo ?? {}).some(v => v > 0)).length;
  const stock = live ? live.inventory?.[state.item_id] ?? 0 : host ? (host.storage?.inventory?.[state.item_id] ?? 0) + (host.storage?.input_buffer?.[state.item_id] ?? 0) + (host.storage?.output_buffer?.[state.item_id] ?? 0) : 0;
  const available = source === 'player' ? inventory?.logistics_bot ?? 0 : (host?.storage?.inventory?.logistics_bot ?? 0) + (host?.storage?.output_buffer?.logistics_bot ?? 0);
  async function submit(commandType: string, execute: () => Promise<CommandResponse>) { if (pending || !canControl) return; setPending(true); try { await submitPlanetCommand({ commandType, planetId, focus: { entityId: building.id }, execute, fetchAuthoritativeSnapshot: () => client.fetchEventSnapshot({ event_types: [...PLANET_COMMAND_RECOVERY_EVENT_TYPES], limit: 50 }) }); } finally { setPending(false); } }
  const invalid = !config.item_id ? config.mode !== 'none' || config.local_storage !== 0 || config.player_delivery_enabled || config.player_collection_enabled : !Number.isSafeInteger(config.local_storage) || config.local_storage < 0;
  return <section className="planet-side-section distributor-controls" aria-label="配送器运行"><div className="section-title">仓库配送器</div><dl className="planet-kv-list"><div><dt>绑定仓库</dt><dd>{host?.id ?? '仓库已失效'}</dd></div><div><dt>当前库存</dt><dd>{getItemDisplayName(catalog, state.item_id)} · {stock}</dd></div><div><dt>航次储能</dt><dd>{state.energy} / {state.energy_capacity}</dd></div><div><dt>机器人</dt><dd>{bots.length} / {state.bot_capacity} · 停靠 {idle}</dd></div></dl>
    <form onSubmit={e => { e.preventDefault(); if (!invalid) void submit('configure_distributor', () => client.cmdConfigureDistributor(building.id, config)); }}><fieldset disabled={!canControl || pending}><legend>配送设置</legend><label>配送物品<select aria-label="配送物品" value={config.item_id} onChange={e => setConfig({ ...config, item_id: e.target.value })}><option value="">未配置</option>{catalog?.items?.filter(i => i.form === 'solid').map(i => <option key={i.id} value={i.id}>{getItemDisplayName(catalog, i.id)}</option>)}</select></label><label>配送模式<select aria-label="配送模式" value={config.mode} onChange={e => setConfig({ ...config, mode: e.target.value as DistributorConfig['mode'] })}><option value="none">关闭</option><option value="supply">供给</option><option value="demand">需求</option></select></label><label>仓库保有量<input type="number" min={0} value={config.local_storage} onChange={e => setConfig({ ...config, local_storage: Number(e.target.value) })} /></label><label><input type="checkbox" checked={config.player_delivery_enabled} onChange={e => setConfig({ ...config, player_delivery_enabled: e.target.checked })} />向机甲补给</label><label><input type="checkbox" checked={config.player_collection_enabled} onChange={e => setConfig({ ...config, player_collection_enabled: e.target.checked })} />回收机甲余量</label><button className="secondary-button" type="submit" disabled={invalid}>应用配送设置</button></fieldset></form>
    <form onSubmit={e => { e.preventDefault(); if (Number.isSafeInteger(count) && count > 0 && count <= available && bots.length + count <= state.bot_capacity) void submit('install_logistics_bot', () => client.cmdInstallLogisticsBot(building.id, count, source)); }}><fieldset disabled={!canControl || pending}><legend>配送机器人</legend><label>机器人来源<select aria-label="机器人来源" value={source} onChange={e => setSource(e.target.value as typeof source)}><option value="player">玩家背包</option><option value="storage">绑定仓库</option></select></label><label>机器人数量<input type="number" min={1} max={state.bot_capacity} value={count} onChange={e => setCount(Number(e.target.value))} /></label><p>可用成品 {available}</p><button className="secondary-button" type="submit" disabled={!Number.isSafeInteger(count) || count < 1 || count > available || bots.length + count > state.bot_capacity}>安装机器人</button><button className="secondary-button" type="button" disabled={!Number.isSafeInteger(count) || count < 1 || count > idle} onClick={() => void submit('uninstall_logistics_bot', () => client.cmdUninstallLogisticsBot(building.id, count))}>回收停靠机器人</button></fieldset></form>
    <ul className="timeline-list timeline-list--dense" aria-label="机器人航程">{bots.map(b => <li key={b.id}><strong>{b.id} · {b.returning ? '返航 · ' : ''}{phase[b.status] ?? b.status}</strong><span>{Object.entries(b.cargo ?? {}).map(([id, n]) => `${getItemDisplayName(catalog, id)} ×${n}`).join('、') || '空载'} · 余能 {b.energy_remaining} · ({b.position.x}, {b.position.y})</span></li>)}</ul></section>;
}
